### ISSUE TITLE
Corrección 

### ISSUE THREAD

**Issue by SergioH1** [luisherreralg/202210-W3CH5-luis-herrera#14]
¡Hola Luis! Estupendo trabajo esta el challenge prácticamente terminado y era todo un reto, pero varias cosas a corregir. 

- Tropecientos anys entiendo que es el primer challenge de fin de semana con tipado pero hay muchisimos y de verdad no cuesta nada crear una interface con las propiedades de tus Pokémon.
- Me gustaría que dentro de unas semanas le echaras un vistazo a tus dos componentes principales PokePrint y PokePrintDetails porque hacen muchísimas cosas es de todo menos single responsibility ,  incluido un método llamado buttons que no tiene perdón  

Por lo demás estupendo se agradece ese poquito de Css y estupendo trabajo ayudando a tus compañeros.

**Comment by luisherreralg** [comment]
@SergioH1 Perdona por la demora en la contestación. Muchas gracias por el feedback, se agradece un montón.  Tenía pensado refactorizar todo y dividir un poco los componentes, pero al final se me fue el tiempo y no me dió tiempo a mas. Lo de los anys es una chorrada, pero me cuesta mucho tiparlos, imagino que con el tiempo los empezaré a ver más claros. Muchas gracias de nuevo!
